export const ADVERTISEMENTS_FETCH_REQUEST = 'ADVERTISEMENTS_FETCH_REQUEST';
export const ADVERTISEMENTS_FETCH_RECEIVE = 'ADVERTISEMENTS_FETCH_RECEIVE';
export const ADVERTISEMENTS_FETCH_REJECT = 'ADVERTISEMENTS_FETCH_REJECT';

export const BUS_MODELS_REQUEST = 'BUS_MODELS_REQUEST';
export const BUS_MODELS_RECEIVE = 'BUS_MODELS_RECEIVE';
export const BUS_MODELS_REJECT = 'BUS_MODELS_REJECT';

export const CATEGORIES_FETCH_REQUEST = 'CATEGORIES_FETCH_REQUEST';
export const CATEGORIES_FETCH_RECEIVE = 'CATEGORIES_FETCH_RECEIVE';
export const CATEGORIES_FETCH_REJECT = 'CATEGORIES_FETCH_REJECT';

export const PHOTO_SEARCH_REQUEST = 'PHOTO_SEARCH_REQUEST';
export const PHOTO_SEARCH_RECEIVE = 'PHOTO_SEARCH_RECEIVE';
export const PHOTO_SEARCH_REJECT = 'PHOTO_SEARCH_REJECT';

export const PHOTO_DETAIL_REQUEST = 'PHOTO_DETAIL_REQUEST';
export const PHOTO_DETAIL_RECEIVE = 'PHOTO_DETAIL_RECEIVE';
export const PHOTO_DETAIL_REJECT = 'PHOTO_DETAIL_REJECT';
